### PR TITLE
Theme setup

### PR DESCRIPTION
**Pull request by mbifulco**

### CODE REVIEW

**Comment by tkeemon** [comment]
The hero image on the landing page looks skewed in Firefox:
aquentfirefoxlandingpageskew

This might have been introduced recently. I don't remember seeing it when I checked the PR last night.

**Comment by tkeemon** [comment]
The hero image on the landing page looks skewed in Firefox:
aquentfirefoxskewedhomepage

Wast this introduced recently? I don't remember seeing it when I checked the PR last night.

**Comment by mbifulco** [comment]
Ah darn it, I've introduced and fixed that a couple times now... I'll patch it out, hold that thought

**Comment by mbifulco** [comment]
@tkeemon just pushed an update

**Comment by tkeemon** [comment]
Looks good!

**Pull request merged**
